# Generated by Django 4.2.11 on 2024-03-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Име и фамилия на потребителя', max_length=50, verbose_name='Име, Фамилия')),
                ('mail', models.CharField(blank=True, default='', help_text='Адрес на електронна поща на потребителя', max_length=30, verbose_name='e-mail')),
                ('username', models.CharField(blank=True, default='', help_text='Потребителско име на потребителя за влизане в системата', max_length=30, verbose_name='Потребителско име')),
                ('password', models.CharField(blank=True, default='', help_text='Парола за влизане в системата', max_length=30, verbose_name='Парола')),
            ],
            options={
                'verbose_name': 'Потребител',
                'verbose_name_plural': 'Потребители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Пореден номер при показване')),
                ('name', models.CharField(blank=True, default='', help_text='Категория - наименование', max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Пореден номер при показване')),
                ('value', models.CharField(blank=True, default='', help_text='Размер (текст)', max_length=10, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размери',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Наименование на артикула за продажба', max_length=50, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена на артикула', max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='', help_text='Описание на предлагания продукт', verbose_name='Описание')),
                ('remark', models.TextField(blank=True, default='', help_text='Текст на съобщение', verbose_name='Забележки')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='main.size')),
            ],
            options={
                'verbose_name': 'Обява',
                'verbose_name_plural': 'Обяви',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Име и фамилия на подателя', max_length=50, verbose_name='Име, Фамилия')),
                ('mail', models.CharField(blank=True, default='', help_text='Адрес на електронна поща за контакт', max_length=30, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, default='', help_text='Телефонен номер за контакт', max_length=30, verbose_name='телефонeн номер')),
                ('message', models.TextField(blank=True, default='', help_text='Съобщение/заитване', verbose_name='Съобщение')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.userpost')),
            ],
            options={
                'verbose_name': 'Зпитване',
                'verbose_name_plural': 'Зпитвания',
            },
        ),
    ]
