# Generated by Django 4.2.11 on 2024-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='test_pics', verbose_name='Снимка'),
        ),
    ]
