# Generated by Django 4.2.11 on 2024-03-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userpost_useer_alter_userpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='main.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='useer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr', to='main.appuser', verbose_name='Потребител'),
        ),
    ]
