# Generated by Django 4.2.11 on 2024-03-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='useer',
            new_name='user',
        ),
    ]
